spring:
  profiles:
    active: local
  # MySQL ?????
  datasource:
    url: jdbc:mysql://localhost:3306/quizmaid?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 114514
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: QuizMaid

  # MyBatis ??
  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.kanade.backend.model.entity
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      use-generated-keys: true

  # MyBatis Plus ??
  mybatis-plus:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.kanade.backend.model.entity
    global-config:
      db-config:
        id-type: AUTO
        logic-delete-field: deleted
        logic-not-delete-value: 0
        logic-delete-value: 1

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.kanade.backend.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8080
  servlet:
    context-path: /api


